#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright (c) 2025 Kk
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

require_relative 'lib/rke2'

Deploy.run
